<?php

namespace AppBundle\Repository;

/**
 * OrderMedicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMedicationsRepository extends \Doctrine\ORM\EntityRepository
{
}
