<?php

namespace AppBundle\Repository;

/**
 * SupplierOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchOrders($term, $role, $user) {
        $query = $this->createQueryBuilder('s')
            ->where('p.'.$role.' = '.$user)
            ->andWhere('s.reference LIKE :searchTerm 
                        OR s.dateAdd LIKE :searchTerm 
                        OR pharmacy.namePharmacy LIKE :searchTerm 
                        OR supplieruser.firstName LIKE :searchTerm 
                        OR supplieruser.name LIKE :searchTerm 
                        OR doctoruser.firstName LIKE :searchTerm 
                        OR doctoruser.name LIKE :searchTerm')
            ->join('s.pharmacy','pharmacy')
            ->join('s.supplier','supplier')
            ->join('supplier.user','supplieruser')
            ->join('s.doctor','doctor')
            ->join('doctor.user','doctoruser')

            ->setParameters(
                array(
                    'searchTerm' => '%'.$term.'%',
                )
            )
            ->getQuery();
        return $query->getResult();
    }
}
