<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.type.datalist_type' shared autowired service.

return $this->services['form.type.datalist_type'] = new \AppBundle\Form\DatalistType();
