<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVwve71a\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVwve71a/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVwve71a.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVwve71a\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVwve71a\appProdProjectContainer(array(
    'container.build_hash' => 'Vwve71a',
    'container.build_id' => '613f7d1e',
    'container.build_time' => 1538089459,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVwve71a');
