<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Supplier extends \AppBundle\Entity\Supplier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'nameSociety', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'bankAccountNumbers', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'medications', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'Order'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'nameSociety', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'bankAccountNumbers', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'medications', '' . "\0" . 'AppBundle\\Entity\\Supplier' . "\0" . 'Order'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Supplier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameSociety($nameSociety)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameSociety', [$nameSociety]);

        return parent::setNameSociety($nameSociety);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameSociety()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameSociety', []);

        return parent::getNameSociety();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankAccountNumbers($bankAccountNumbers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankAccountNumbers', [$bankAccountNumbers]);

        return parent::setBankAccountNumbers($bankAccountNumbers);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccountNumbers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccountNumbers', []);

        return parent::getBankAccountNumbers();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\AppBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedications(\AppBundle\Entity\SupplierStock $medications = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedications', [$medications]);

        return parent::setMedications($medications);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedications', []);

        return parent::getMedications();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedication(\AppBundle\Entity\SupplierStock $medication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedication', [$medication]);

        return parent::addMedication($medication);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedication(\AppBundle\Entity\SupplierStock $medication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedication', [$medication]);

        return parent::removeMedication($medication);
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\AppBundle\Entity\SupplierOrder $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$order]);

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\AppBundle\Entity\SupplierOrder $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$order]);

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

}
