<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvkk8w2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvkk8w2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBvkk8w2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBvkk8w2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBvkk8w2\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bvkk8w2',
    'container.build_id' => 'eaa7ba09',
    'container.build_time' => 1538087356,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBvkk8w2');
