<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKq29iku\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKq29iku/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKq29iku.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKq29iku\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKq29iku\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kq29iku',
    'container.build_id' => 'a3eff89f',
    'container.build_time' => 1538349323,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKq29iku');
